import = ["/home/mrochford/.config/alacritty/themes/themes/omni.yaml"]
[font]
size = 12.0

[font.normal]
family = "Iosevka Term"
style = "Regular"

[window]
opacity = 1

[window.dimensions]
columns = 80
lines = 20

[window.padding]
x = 10
y = 10
