#! /bin/sh

xfce4-panel &
xmodmap ~/.Xmodmap
xset r rate 300 60

# xdg_autostart
xss-lock -- kush_lock &
xfce4-power-manager
~/.fehbg

compton &
nm-applet &
pgrep sxhkd || sxhkd &
pgrep volumeicon || volumeicon &

bspc monitor -d I II III IV V VI VII VIII IX
bspc desktop II -l monocle

bspc config focus_follows_pointer true

bspc config border_width         2
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^2'
bspc rule -a net-runelite-client-RuneLite state=floating
bspc rule -a feh state=floating rectangle=400x400
bspc rule -a Transmission state=floating
