#!/usr/bin/env sh

export MOZ_ENABLE_XINPUT2=1

export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"

export PATH="$PATH:$HOME/go/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:/usr/lib/rustup/bin"

export EDITOR="vim"
export BROWSER="firefox"

export FZF_DEFAULT_OPTS="--cycle --height=40% --reverse --border"
command -v rtx >/dev/null 2>&1 && eval "$(rtx activate)"
command -v rg >/dev/null 2>&1 && export FZF_DEFAULT_COMMAND="rg --color=never --files ."
command -v bat >/dev/null 2>&1 && export MANPAGER="sh -c 'col -bx | bat -l man -p'"

export MAKEFLAGS="-j8"

alias tmux="tmux -f $XDG_CONFIG_HOME/tmux/tmux.conf"
alias grep="grep --color=auto"
