#!/usr/bin/env sh

export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CONFIG_HOME="$HOME/.config"

export PATH="$PATH:$HOME/scripts"
export PATH="$PATH:$HOME/go/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/.local/bin"

export EDITOR="nvim"
export BROWSER="chromium"

export FZF_DEFAULT_OPTS="--cycle --height=40% --reverse --border"
command -v rg >/dev/null 2>&1 && export FZF_DEFAULT_COMMAND="rg --color=never --files ."
command -v bat >/dev/null 2>&1 && export MANPAGER="sh -c 'col -bx | bat -l man -p'"

export MAKEFLAGS="-j8"

alias tmux="tmux -f $XDG_CONFIG_HOME/tmux/tmux.conf"

alias ls='ls -hN --color=auto --group-directories-first'
alias ll='ls -l'
alias la='ll -a'
alias grep="grep --color=auto"
