#! /bin/sh

xbindkeys
xset r rate 300 60
xfce4-power-manager
~/.fehbg 

sxhkd &
compton &
light-locker &
launchpolybar &
redshift-gtk &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc desktop II -l monocle

bspc config border_width          0
bspc config window_gap            6
bspc config bottom_padding        50
bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

bspc rule -a Gimp state=floating follow=on
bspc rule -a mpv state=floating follow=on
bspc rule -a feh state=floating follow=on
bspc rule -a Sxiv state=floating follow=on
bspc rule -a Zathura state=tiled 
bspc rule -a Firefox desktop='^2'

