#! /bin/sh

wid=$1
class=$2
instance=$3

notify-send "starting fuck u"
if [ "$instance" = Alacritty ] ; then
    title=$(xdotool getwindowname "$wid")
    notify-send "starting fuck u"
    case "$title" in
        scratch-term)
            notify-send "asdf"
            echo "state=floating"
            ;;
    esac
fi
