let mapleader = " "
set mouse=nv

" Visual mode pressing * or # searches for the current selection
" Super useful! From an idea by Michael Naumann
vnoremap <silent> * :<C-u>call VisualSelection('', '')<CR>/<C-R>=@/<CR><CR>
vnoremap <silent> # :<C-u>call VisualSelection('', '')<CR>?<C-R>=@/<CR><CR>

" Disable highlight when <leader><cr> is pressed
map <silent> <leader><cr> :noh<cr>

" Smart way to move between windows
map <C-j> <C-W>j
map <C-h> <C-W>h
map <C-k> <C-W>k
map <C-l> <C-W>l

" Fast saving
nmap <leader>w :w<cr>
" delete all buffers
nmap <leader>X :bufdo bd<cr>
" delete all buffers but current
nmap <leader>x :%bd\|e#\|bd# <cr> 

set path=.,**
map <leader>e :e <c-r>=expand("%:p:h")<cr>/
map <leader>b :b<space>
map <leader>. :find **/
map <leader>> :find<space>

" Move a line of text using ALT+[jk] or Command+[jk] on mac
nmap <M-j> mz:m+<cr>`z
nmap <M-k> mz:m-2<cr>`z
vmap <M-j> :m'>+<cr>`<my`>mzgv`yo`z
vmap <M-k> :m'<-2<cr>`>my`<mzgv`yo`z

" Tabbing out lines
vnoremap > >gv
vnoremap < <gv
nnoremap <Tab> >>_
nnoremap <S-Tab> <<_
inoremap <S-Tab> <C-D>
vnoremap <Tab> >gv
vnoremap <S-Tab> <gv

nnoremap / /\v

map 0 ^

" Return to last edit position when opening files (You want this!)
au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

" Set 7 lines to the cursor - when moving vertically using j/k
set so=7

set splitbelow splitright

set updatetime=300
set shortmess+=c
set signcolumn=auto

set list
" set listchars=tab:>-,trail:~,space:.

set foldmethod=syntax
set foldlevel=8

set number
set relativenumber

set clipboard+=unnamedplus

" Height of the command bar
set cmdheight=1
" A buffer becomes hidden when it is abandoned
set hidden

set whichwrap+=<,>,h,l

set ignorecase
set smartcase

set hlsearch

" Don't redraw while executing macros (good performance config)
set lazyredraw

" For regular expressions turn magic on
set magic

" No annoying sound on errors
set noerrorbells
set novisualbell

" Use Unix as the standard file type
set ffs=unix,dos,mac

set nobackup
set nowb
set noswapfile

set undodir=~/.local/share/vim/undo
set undofile

" tabs
set tabstop=8 softtabstop=0 expandtab shiftwidth=4

set textwidth=100
set colorcolumn=+1

set wrap
set background=dark
set termguicolors
