#!/bin/sh

# Profile file. Runs on login.

export PATH="$PATH:$HOME/scripts"
export EDITOR="vim"
export TERM="st"
export BROSWER="firefox"

setfont latarcyrheb-sun32

export PATH="$HOME/.cargo/bin:$PATH"
